/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DatasetBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Datasets": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MedicalAI": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "Models": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
