# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV AWS_DEFAULT_REGION=us-east-1
ENV NOTEBOOK_URL=""
ENV DATASET_URL=""

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install boto3 jupyter nbconvert pandas nbformat

# Create a working directory
WORKDIR /app

# Script to download the notebook and dataset from S3
COPY setup.py /app/
# Ensure the script is executable
RUN chmod +x /app/setup.py

EXPOSE 8888

# Entry point to execute python script
CMD ["python", "/app/setup.py"]